name: "CLI build"

on:
  workflow_dispatch: {}
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: install prerequisites
        run: apk add g++ git make cmake ninja
      - uses: actions/checkout@v4
        with:
          repository: duckdb/duckdb
          ref: ${{ github.ref_name }}
      - run: make
        env:
          GEN: ninja
      - name: test
        run: |
          build/release/duckdb --version
          mv build/release/duckdb duckdb-linux-amd64
      - name: add release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ github.ref_name }}"
          files: |
            ./duckdb-linux-amd64
