name: "CLI build"

on:
  workflow_dispatch: {}
  push:
    tags:
      - "*"
  pull_request: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: install prerequisites
        run: apk add g++ git make cmake ninja openssl openssl-dev zlib zlib-dev aws-sdk-cpp aws-sdk-cpp-dev aws-crt-cpp-dev
      - uses: actions/checkout@v4
        with:
          repository: duckdb/duckdb
          ref: v1.1.3
      - run: make
        env:
          GEN: ninja
          CORE_EXTENSIONS: 'aws;autocomplete;httpfs;json'
      - name: test
        run: |
          build/release/duckdb --version
          mv build/release/duckdb duckdb-linux-amd64
          mv build/release/extension/*/*.duckdb_extension .
          tree build/release/extension/
